name: Build Android APK
on:
  workflow_dispatch:
  push: { branches: [ "main" ] }
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android
      ANDROID_HOME: /usr/local/lib/android
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: "17" }
      - name: Detect project directory
        id: detect
        run: |
          set -e
          FILE="$(git ls-files | grep -E '(^|/)(settings\.gradle(\.kts)?)$' | head -n1 || true)"
          [ -n "$FILE" ] || { echo "No settings.gradle found"; exit 1; }
          DIR="$(dirname "$FILE")"; [ "$DIR" = "" ] || [ "$DIR" = "." ] || true
          echo "project_dir=${DIR:-.}" >> $GITHUB_OUTPUT
      - name: Install Android cmdline-tools
        run: |
          sudo mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT/cmdline-tools
          sudo curl -L -o cmdtools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          sudo unzip -q cmdtools.zip && sudo rm cmdtools.zip
          sudo mv cmdline-tools latest
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
      - run: yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --licenses
      - run: |
          "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" \
            "platform-tools" "platforms;android-34" "build-tools;34.0.0"
      - name: Install Gradle
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.7
      - name: Build Debug APK
        run: gradle assembleDebug --stacktrace
        working-directory: ${{ steps.detect.outputs.project_dir }}
      - uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: ${{ steps.detect.outputs.project_dir }}/app/build/outputs/apk/debug/app-debug.apk
